version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
        - "*"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: "weekly"
