#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        # Stop service before removal
        if [ -d /run/systemd/system ]; then
            deb-systemd-invoke stop changedetection.io.service >/dev/null || true
        fi
        ;;

    upgrade|failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
